export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
export const GET_PRODUCT = "GET_PRODUCT";

export const CART_ITEM_ADD = "CART_ITEM_ADD";
export const CART_ITEM_REMOVE = "CART_ITEM_REMOVE";
export const CART_ITEM_LOADING = "CART_ITEM_LOADING";
export const CART_ITEM_FAIL = "CART_ITEM_FAIL";
export const CART_SAVE_ADDRESS = "CART_SAVE_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
export const CLEAR_MESSAGE_CART = "CLEAR_MESSAGE_CART";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const LOGIN_USER_LOAD = "LOGIN_USER_LOAD";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_LOAD = "UPDATE_USER_LOAD";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CREATE_ORDER_LOAD = "CREATE_ORDER_LOAD";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
export const ORDER_RESET = "ORDER_RESET";

export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const GET_ORDER_SUCCESS = "GET_ORDER_SUCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";

export const PAY_ORDER_SUCCESS = "PAY_ORDER_SUCCESS";
export const PAY_ORDERS_FAIL = "PAY_ORDER_FAIL";
export const PAY_ORDER_LOAD = "PAY_ORDER_LOAD";

//----------admin---------------
export const GET_USERS_LOAD = "GET_USERS_LOAD";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const GET_USER_LOAD = "GET_USER_LOAD";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_USER_RESET = "GET_USER_RESET";

export const UPDATE_ADMIN_USER_SUCCESS = "UPDATE_ADMIN_USER_SUCCESS";
export const UPDATE_ADMIN_USER_FAIL = "UPDATE_ADMIN_USER_FAIL";

export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const ADD_PRODUCT_RESET = "ADD_PRODUCT_RESET";

export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAIL = "GET_ALL_ORDERS_FAIL";

export const DELIVER_ORDERS_SUCESS = "DELIVER_ORDER_SUCESS";
export const DELIVER_ORDERS_FAIL = "DELIVER_ORDER_FAIL";
