export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';
export const GET_PRODUCT = 'GET_PRODUCT';

export const CART_ITEM_ADD = 'CART_ITEM_ADD';
export const CART_ITEM_REMOVE = 'CART_ITEM_REMOVE';
export const CART_ITEM_LOADING = 'CART_ITEM_LOADING';
export const CART_ITEM_FAIL = 'CART_ITEM_FAIL';

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const LOGIN_USER_LOAD = "LOGIN_USER_LOAD";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_LOAD = "UPDATE_USER_LOAD";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";