export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';
export const GET_PRODUCT = 'GET_PRODUCT';

export const CART_ITEM_ADD = 'CART_ITEM_ADD';
export const CART_ITEM_REMOVE = 'CART_ITEM_REMOVE';
export const CART_ITEM_LOADING = 'CART_ITEM_LOADING';
export const CART_ITEM_FAIL = 'CART_ITEM_FAIL';